spring:
  application:
    name: autraining-server-center


server:
  port: ${PORT}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${PORT}/eureka/
